# Generated by Django 3.1.5 on 2021-01-22 13:28

from django.db import migrations, models
import people.validators


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(max_length=12, unique=True, validators=[people.validators.validate_int, people.validators.validate_iin]),
        ),
    ]
